### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'dicts')

### ISSUE THREAD

**Issue by zhaoeryu** [moxun1639/vue-data-dict#1]
我尝试把该组件引入到项目中，但是报了如下错误：
<img width="670" alt="image" src="https://github.com/moxun1639/vue-data-dict/assets/49333146/56a23a58-7076-489e-9ac0-babb68e0e6bf">

经过排查代码，建议对`this.$options`判断下非空
<img width="843" alt="image" src="https://github.com/moxun1639/vue-data-dict/assets/49333146/bb4bdcfd-ea8f-4f13-8624-2ca346dd45cc">

**Comment by moxun1639** [comment]
好的

**Comment by moxun1639** [comment]
@zhaoeryu 已发布v1.2.1，可以安装新版本

v2.0.0已在路上，会有一些新功能，有什么需求欢迎提出

**Comment by zhaoeryu** [comment]
Good job！

v2版本上线的时候，建议把v2更新的功能列举出来，v1升级到v2需要注意的事项
